--- 
title: "HackBookEasyPeasy - EasyPeasyWay"
subtitle: "https://sites.google.com/site/hackbookeasypeasy/home"
author: "hack-author"
#date: "`r Sys.Date()`"
output:
  bookdown::gitbook:
    config:
      sharing: false
      fontsettings:
        theme: night
        family: sans
        size: 2
    fig_caption: false
  pdf_document:
    includes:
      in_header: preamble.tex
      toc: true
      number_sections: true
      fig_caption: false
      latex_engine: xelatex
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  The original hackbook easy peasy in bookdown format.,
link-citations: yes
github-repo: "gogogosho/ezpz"
site: bookdown::bookdown_site
# cp -TRv _book docs
# file.create('.nojekyll') 
---

# Introduction {-}

<!-- **Port of the original hackbook easy peasy (google sites one)** -->
<!-- comments with ctrl + shift + c -->
*I am Allen Carr. I am also not Allen Carr. So yes I am not the author. I am the hack-author*

*I hacked Allen Carr’s book and his method of de-addiction to adapt it for PMO.	Why? Because his method helped me in getting rid of cigarettes, alcohol and then	PMO. Why did I hack his work? Because he is dead now. And the institution that he had	formed does not list Internet pornography as one of the addictions that it provides	services for. I don't gain monetarily or otherwise. Above all - you won’t ‘find’ me in this	book. Myself and Allen will appear and disappear in this book to provide you with an	unique and effective method to get your mind de-addicted.*
<br/><br/>
<center>
**IMPORTANT ADVICE FOR YOU!**<br/>

**DO NOT JUMP CHAPTERS!**<br/>

**THE NUMBERS TO UNLOCK THE COMBO LOCK SHOULD BE USED IN THE GIVEN SEQUENCE!**
</center>
<br/><br/>
*The common thread running through Allen Carr's work is the removal of fear. Indeed, his genius lies in eliminating the phobias and anxieties which prevent people from being able to enjoy life to the full, as his best-selling books vividly demonstrate. His method is solid and has high success rates. It helped cure me of not one but three addictions. There is a network of clinics that uses his methods that span the globe and has a phenomenal reputation for success in helping people to quit addictions (except PMO). Their success rate is over 95\% with money-back guarantees.*

**Hackbook: A book based and hacked from another book. The original author is credited fully.**
<br/><br/>

<center>
**IMPORTANT ADVICE FOR YOU!**<br/>

**DO NOT JUMP CHAPTERS!**<br/>

**THE NUMBERS TO UNLOCK THE COMBO LOCK SHOULD BE USED IN THE GIVEN SEQUENCE!**
</center>

<br/><br/>
*Dr. Albert Ellis' autobiography - "All Out!"*

_“I used to wrongly think that most of them (addicts) were aided by self-help groups like AA, by therapy, or some other real support. But no. The facts show that more people surrender their addictions on their own-without any notable help from others. How? Mainly by **seeing, acknowledging, and emphasizing** how hard it is **not** to stop and how much **easier** it is-in the long run- to suffer through the withdrawal process.”_
	